name: Basic Checkout Lab

on:
  push:
    branches:
      - main

jobs:
  basic-checkout:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Making script executable
        run: chmod +x scripts/greeting.sh
      
      - name: Running script
        run: ./scripts/greeting.sh
