name: Docker Nginx Lab and K8s Info

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build Image
      - name: Build Docker image
        run: docker build -t mynginx:test .
      
      # Push Image
      - name: Push to DockerHub
        run: |
          docker tag mynginx:test ${{ secrets.DOCKER_USERNAME }}/mynginx:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mynginx:latest

  k8s-info:
    needs: docker-build  # This makes k8s-info wait for docker-build to succeed
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Configure kubectl
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
      
    - name: Get kubectl version
      run: |
        kubectl version
        
    - name: Get node information
      run: |
        echo "Getting node information..."
        kubectl get nodes -o wide
        
        echo "Getting detailed node description..."
        kubectl describe nodes
        
    - name: Get cluster info
      run: |
        echo "Getting cluster information..."
        kubectl cluster-info